### PR TITLE
ContextPath Prefixed - Multiple Occurrences - For Non Cloud

### PR DESCRIPTION
**Pull request by friendlymahi**
- For multiple calls via $.ajax/.getJson & more
- Fixes Issue #64

### CODE REVIEW

**Comment by friendlymahi** [comment]
@dcolvinbc - As advised, moved the changes using the new branch. Once these changes are merged to OnPrem/Non Cloud version, then I can make the changes in cloud version as well. Thanks !

**Comment by friendlymahi** [comment]
@hngrylobster @dcolvinbc - Hope you are doing well. Any luck with the review and plan on when we can expect these in new version for use. Thanks!

**Comment by dcolvinbc** [comment]
@friendlymahi Sorry for the late response. I had a concern i had put on the other PR about not null checking CQ.shared.HTTP.getContextPath() before you put in a string. I think we should put in something that will check if is null or empty dont put in the string. I know that sounds like an odd request but I want to make sure we do not affect other customers as well. Something like this below would be good on those.

image

**Comment by friendlymahi** [comment]
Sure np.. It's a fair ask. I will make the changes and send back 😊

**Comment by friendlymahi** [comment]
@dcolvinbc - Looks like there were more occurences to this method CQ.shared.HTTP.getContextPath() than the ones I added. So added a common falsy check to all these occurrences by replacing them with an empty character '' when the expression is evaluated as falsy. Please review now and let me know if more changes are necessary.

Thanks !

**Comment by friendlymahi** [comment]
Good morning. Any update on this request? Another question. I know it may not happen but will ask 😊. Do you intend to atleast keep the core bundle on nexus or an externally accessible public repository for us to add bright cove as a dependency on our code base?

Thanks!

**Review by dcolvinbc — APPROVED** [review]

**Comment by friendlymahi** [comment]
@dcolvinbc - Thank you so much for the support. Any update on my query regarding public access of the binary artifacts via nexus or maven central??

Thanks in advance!

**Comment by hngrylobster** [comment]
We will update our own Nexus with the compiled artifacts - yep. However, we do not provide any sort of SLA on its availability.

**Comment by friendlymahi** [comment]
Np. When they are published please reply back here  or update your docs. Additionally any time line on when this release will be published so we can download the artifact for our environment?

Thanks!

**Pull request merged**
