### PR TITLE
ContextPath Prefixed for multiple calls via $.ajax/.getJson & more

### PR DESCRIPTION
**Pull request by friendlymahi**
- Fixes Issue #64

### CODE REVIEW

**Comment by friendlymahi** [comment]
@hngrylobster - Requesting you to review these changes and advise for any addl fixes. We recently upgraded our AEM to v6.5 SP17 and long due on upgrading Brightcove. With this fix we'll be clean without having to make any changes on clientlibs and manage your code copy on our end.

Thanks in advance !

**Comment by friendlymahi** [comment]
@hngrylobster - Happy New Year ! We wanted to know if you intend to review and advise on these fixes so we can communicate to our leadership team on the next upgrade/version bump of brightcove in our org. Thanks !!

**Comment by dcolvinbc** [comment]
@friendlymahi I asked a question on this to possibly resolve. Also if this is for on prem please cancel this pr do changes on your own branch from release/6.0.5 and do your pr to merge into this branch. If clould do the changes from release/6.1.2-cloud. We will be working on combining these branches in the future so that one single master will work. Thank you

**Comment by friendlymahi** [comment]
@dcolvinbc - sure. Will send a new pr as this is for onprem. Also shall I send the PR back to release/6.0.5 itself or master? !

**Comment by dcolvin** [comment]
The PR should be to merge to release/6.0.5.

**Comment by friendlymahi** [comment]
Thanks again for taking time to respond. I will send a PR today.

**Comment by friendlymahi** [comment]
Closing this PR in favor of the new one.
https://github.com/brightcove/Adobe-AEM-Brightcove-Connector/pull/66

Thanks !

**Pull request closed without merging**
